const {createEnv} = require("../lib/env")
const globalEnv = createEnv()
const {initGlobalEnv}= require("../lib/init")
initGlobalEnv(globalEnv)
var println = globalEnv.getEnv("println")
console.log(println)